export const accountsDefault = {
	created_at: '',
	description: '',
	name: '',
	type: '',
	user_id: '',
};
export const asset_classesDefault = {
	cash: null,
	commodities: null,
	created_at: '',
	crypto: null,
	equityDeveloped: null,
	equityEmerging: null,
	equityOther: null,
	equityUS: null,
	fixedIncomeGlobal: null,
	fixedIncomeUS: null,
	other: null,
	realEstateGlobal: null,
	realEstateUS: null,
	symbol: '',
};
export const blogDefault = {
	author: '',
	author_img: '',
	created_at: '',
	date: '',
	description: '',
	hero_img: '',
	md: '',
	tags: [],
	title: '',
	url: '',
};
export const portfoliosDefault = {
	account_id: null,
	cost_basis: null,
	created_at: '',
	description: '',
	market_value: null,
	name: '',
};
export const positionsDefault = {
	cost_basis: null,
	created_at: '',
	market_value: null,
	name: '',
	portfolio_id: null,
	price: null,
	quantity: null,
	security_type: '',
	symbol: '',
};
export const profilesDefault = {
	accepted_tos: false,
	address: '',
	dob: '',
	email: '',
	employment_status: '',
	full_name: '',
	id: '',
	income: null,
	is_active: false,
	job_title: '',
	net_worth: null,
	phone: '',
	tax_filing_status: '',
};
export const transactionsDefault = {
	action: '',
	amount: null,
	date: '',
	description: '',
	fees: null,
	portfolio_id: null,
	price: null,
	quantity: null,
	symbol: '',
};
