export const accountsDefault = {
	asset_class: [],
	cost_basis: null,
	created_at: '',
	description: '',
	market_value: null,
	name: '',
	type: '',
	user_id: '',
};
export const assetsDefault = {
	asset_class: [],
	country: '',
	created_at: '',
	cusip: '',
	description: '',
	industry: '',
	last_updated: '',
	name: '',
	primary_asset_class: '',
	sector: '',
	security_type: '',
	symbol: '',
};
export const balancesDefault = {
	balance: null,
	benchmarks: [],
	created_at: '',
	date: '',
	flows: null,
	portfolio_id: null,
};
export const blogDefault = {
	author: '',
	author_img: '',
	created_at: '',
	date: '',
	description: '',
	hero_img: '',
	md: '',
	tags: [],
	title: '',
	url: '',
};
export const portfoliosDefault = {
	account_id: null,
	asset_class: [],
	cost_basis: null,
	created_at: '',
	description: '',
	market_value: null,
	name: '',
};
export const positionsDefault = {
	asset_class: [],
	cost_basis: null,
	created_at: '',
	market_value: null,
	name: '',
	portfolio_id: null,
	price: null,
	quantity: null,
	security_type: '',
	symbol: '',
};
export const pricesDefault = {
	created_at: '',
	date: '',
	pct: null,
	price: null,
	symbol: '',
};
export const profilesDefault = {
	accepted_tos: false,
	address: '',
	dob: '',
	email: '',
	employment_status: '',
	full_name: '',
	id: '',
	income: null,
	is_active: false,
	job_title: '',
	net_worth: null,
	phone: '',
	tax_filing_status: '',
};
export const transactionsDefault = {
	action: '',
	amount: null,
	created_at: '',
	date: '',
	portfolio_id: null,
	symbol: '',
};
