DROP table if exits accounts, portfolios, balances, positions, transactions;

create table
public.accounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  user_id uuid null,
  name text null,
  description text null,
  type text null,
  market_value numeric null,
  cost_basis numeric null,
  asset_class jsonb null,
  constraint accounts_pkey primary key (id),
  constraint accounts_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) tablespace pg_default;

create table
public.portfolios (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  account_id bigint null,
  user_id uuid null,
  name character varying null,
  description text null,
  type text null,
  market_value numeric null,
  cost_basis numeric null,
  asset_class jsonb null,
  constraint portfolios_pkey1 primary key (id),
  constraint portfolios_account_id_fkey foreign key (account_id) references accounts (id) on delete cascade,
  constraint portfolios_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) tablespace pg_default;

create table
  public.balances (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    portfolio_id bigint null,
    account_id bigint null,
    user_id uuid null,
    date date not null,
    balance double precision not null,
    flows double precision not null,
    benchmarks jsonb not null,
    total boolean null,
    constraint balances_pkey primary key (id),
    constraint balances_portfolio_id_fkey foreign key (portfolio_id) references portfolios (id) on delete cascade,
    constraint balances_account_id_fkey foreign key (account_id) references accounts (id) on delete cascade,
    constraint balances_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.positions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    portfolio_id bigint null,
    account_id bigint null,
    user_id uuid null,
    symbol character varying null,
    name character varying null,
    quantity real null,
    price real null,
    market_value numeric null,
    cost_basis numeric null,
    security_type text null,
    asset_class jsonb null,
    price_7d double precision null,
    constraint positions_pkey primary key (id),
    constraint positions_portfolio_id_fkey foreign key (portfolio_id) references portfolios (id) on delete cascade,
    constraint positions_account_id_fkey foreign key (account_id) references accounts (id) on delete cascade,
    constraint positions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

  create table
  public.transactions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    portfolio_id bigint null,
    account_id bigint null,
    user_id uuid null,
    action text null,
    symbol text null,
    amount double precision null,
    date date null,
    constraint transactions_pkey primary key (id),
    constraint transactions_portfolio_id_fkey foreign key (portfolio_id) references portfolios (id) on delete cascade,
    constraint transactions_account_id_fkey foreign key (account_id) references accounts (id) on delete cascade,
    constraint transactions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

create table
  public.prices (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    date date null,
    symbol text null,
    price double precision null,
    pct double precision null,
    constraint prices_pkey primary key (id)
  ) tablespace pg_default;

create table
public.assets (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  symbol text null,
  name text null,
  country text null,
  description text null,
  security_type text null,
  sector text null,
  industry text null,
  cusip text null,
  asset_class jsonb null,
  last_updated timestamp with time zone null default now(),
  primary_asset_class text null,
  constraint assets_pkey primary key (id),
  constraint assets_symbol_key unique (symbol)
) tablespace pg_default;

create table
  public.profiles (
    id uuid not null,
    full_name text null,
    dob date null,
    accepted_tos boolean not null default false,
    is_active boolean null default false,
    phone text null,
    address text null,
    income bigint null,
    employment_status text null,
    job_title text null,
    net_worth bigint null,
    tax_filing_status text null,
    email text null,
    settings jsonb null,
    constraint profiles_pkey primary key (id),
    constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade
  ) tablespace pg_default;