name: Check for console.log

on: pull_request

jobs:
  check-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Search for console.log
        run: |
<<<<<<< HEAD
          if grep -r --exclude-dir=./data --exclude-dir=./src/routes/api "console.log" .; then
=======
          if grep -r --exclude-dir=./src/routes/api "console.log" ./src; then
>>>>>>> c25243382d7bc19a3f28402cf9dc2deb753a55ae
            echo "console.log statement found!"
            exit 1
          else
            echo "No console.log statements found."
          fi
